# -*- coding: utf-8 -*-
"""Fraud_trial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HKRqRaows47-ehXICa73ApQXGg0EKKSP
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split, RandomizedSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import RandomUnderSampler
from scipy.stats import randint, uniform
from scipy import stats

df = pd.read_csv('test.csv')

df.head()

df.describe()

features = ['Transaction Amount', 'Quantity', 'Customer Age', 'Account Age Days', 'Transaction Hour']

fig, axes = plt.subplots(nrows=3, ncols=2, figsize=(16, 12))
axes = axes.flatten()

for i, feature in enumerate(features):
    sns.boxplot(x=feature, data=df, ax=axes[i])
    axes[i].set_title(f'Box Plot of {feature}')

plt.tight_layout()
plt.show()

df.info()

df.isna().sum()

df = df.drop(["Transaction ID","Customer ID","Customer Location","Transaction Date","IP Address","Shipping Address","Billing Address"], axis=1)

df.head()

df['Quantity_Log'] = np.log1p(df['Quantity'])
df['Account_Age_Weeks'] = df['Account Age Days'] // 7
df['Age_Category'] = pd.cut(df['Customer Age'], bins=[0, 25, 35, 50, 65, np.inf], labels=['Young', 'Young_Adult', 'Adult', 'Senior', 'Elder'])

df['Age_Category'] = df['Age_Category'].astype('object')

df.info()

categorical = df.select_dtypes(include=['object']).columns.tolist()
categorical

df['Payment Method'].value_counts()

df['Payment Method'] = df['Payment Method'].map({"debit card":0,"credit card":1,"PayPal":2,"bank transfer":3})

df['Product Category'].value_counts()

df['Product Category'] = df['Product Category'].map({"home & garden":0,"electronics":1,"toys & games":2,"clothing":3,"health & beauty":4})

df['Device Used'].value_counts()

df['Device Used'] = df['Device Used'].map({"desktop":0,"mobile":1,"tablet":2,})

age_map = {
    'Young': 0,
    'Young_Adult': 1,
    'Adult': 2,
    'Senior': 3,
    'Elder': 4
}
df['Age_Category'] = df['Age_Category'].map(age_map)

df['Amount_zscore'] = stats.zscore(df['Transaction Amount'], nan_policy='omit')

def bin_hour(hour):
    if hour <= 6:
        return 'Night'
    elif hour <= 12:
        return 'Morning'
    elif hour <= 18:
        return 'Afternoon'
    else:
        return 'Evening'

# Create and map in one go
hour_map = {'Night': 0, 'Morning': 1, 'Afternoon': 2, 'Evening': 3}
df['Hour_Bin'] = df['Transaction Hour'].apply(bin_hour).map(hour_map)

new_column_order = ['Transaction Amount', 'Amount_zscore','Payment Method', 'Product Category', 'Quantity','Quantity_Log',
                   'Customer Age', 'Age_Category','Device Used', 'Account Age Days','Account_Age_Weeks',
                   'Transaction Hour','Hour_Bin','Is Fraudulent']
df = df.reindex(columns=new_column_order)
df

numeric_features = ['Transaction Amount', 'Quantity', 'Customer Age', 'Account Age Days', 'Transaction Hour']
scaler = StandardScaler()
df[numeric_features] = scaler.fit_transform(df[numeric_features])
df.head()

X = df.drop('Is Fraudulent', axis=1)
y = df['Is Fraudulent']
X.shape, y.shape

df.isna().sum()

df['Age_Category'].value_counts()

df = df.dropna()

smote = SMOTE()
X_resampled, y_resampled = smote.fit_resample(X, y)
print(X_resampled.shape,y_resampled.shape)

rus = RandomUnderSampler(sampling_strategy='majority')
X_under_resampled, y_under_resampled = rus.fit_resample(X, y)
print(X_under_resampled.shape,y_under_resampled.shape)

print(y_resampled.value_counts())
print(y_under_resampled.value_counts())

X_train,X_test,y_train,y_test = train_test_split(X_under_resampled,y_under_resampled,test_size=0.2,random_state=42)
model = RandomForestClassifier(random_state=1234)
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print(classification_report(y_test,y_pred))

# SMOTE
X_train,X_test,y_train,y_test = train_test_split(X_resampled,y_resampled,test_size=0.2,random_state=42)
model_smote = RandomForestClassifier(n_estimators=500, max_depth=30, n_jobs=-1)
model_smote.fit(X_train,y_train)
y_pred = model.predict(X_test)
print(classification_report(y_test,y_pred))

X_train,X_test,y_train,y_test = train_test_split(X_resampled,y_resampled,test_size=0.2,random_state=42)

from sklearn.linear_model import LogisticRegression
model_logistic = LogisticRegression(max_iter=1000, solver='liblinear')
model_logistic.fit(X_train, y_train)
y_pred = model.predict(X_test)
print(classification_report(y_test,y_pred))

from xgboost import XGBClassifier
model_xgbooster =  XGBClassifier(n_estimators=1000, max_depth=15, learning_rate=0.01, tree_method='hist', use_label_encoder=False)
model_xgbooster.fit(X_train, y_train)
y_pred = model.predict(X_test)
print(classification_report(y_test,y_pred))

from keras.models import Sequential
from keras.layers import Dense, Dropout, BatchNormalization, Input
from sklearn.metrics import roc_auc_score, precision_score, recall_score, f1_score, roc_curve, auc, accuracy_score, confusion_matrix
import tensorflow as tf

class NeuralNetworkModel:
    def __init__(self, input_dim):
        self.model = Sequential([
            Input(shape=(input_dim,)),
            Dense(1024, activation='relu'),
            BatchNormalization(),
            Dropout(0.5),
            Dense(512, activation='relu'),
            BatchNormalization(),
            Dropout(0.5),
            Dense(256, activation='relu'),
            BatchNormalization(),
            Dropout(0.5),
            Dense(1, activation='sigmoid')
        ])
        self.model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['AUC'])

    def train(self, X_train, y_train, X_test, y_test):  # using test set as validation
        early_stopping = tf.keras.callbacks.EarlyStopping(
            monitor='val_loss', patience=10, restore_best_weights=True
        )
        self.model.fit(
            X_train, y_train,
            epochs=200,
            batch_size=256,
            validation_data=(X_test, y_test),  # using test set here
            callbacks=[early_stopping],
            verbose=0
        )

    def evaluate(self, X_test, y_test):  # evaluation remains the same
        y_prob = self.model.predict(X_test).flatten()
        y_pred = (y_prob > 0.5).astype(int)
        fpr, tpr, _ = roc_curve(y_test, y_prob)
        roc_auc = auc(fpr, tpr)
        accuracy = accuracy_score(y_test, y_pred)
        precision = precision_score(y_test, y_pred)
        recall = recall_score(y_test, y_pred)
        f1 = f1_score(y_test, y_pred)
        confusion = confusion_matrix(y_test, y_pred)
        return {
            'ROC AUC': roc_auc,
            'Accuracy': accuracy,
            'F1 Score': f1,
            'Precision': precision,
            'Recall': recall,
            'y_prob': y_prob,
            'Confusion Matrix': confusion
        }

X_train, X_val, y_train, y_val = train_test_split(
    X_resampled,y_resampled, test_size=0.2, random_state=42
)

# Train neural network model using unscaled data
input_dim = X_train.shape[1]
nn_model = NeuralNetworkModel(input_dim=input_dim)
nn_model.train(X_train, y_train, X_val, y_val)

# Evaluate neural network model on the unscaled test set
nn_results = nn_model.evaluate(X_test, y_test)

# Evaluate neural network model
nn_results = nn_model.evaluate(X_val, y_val)

nn_results = nn_model.evaluate(X_test, y_test)

# Get confusion matrix from the evaluation result
conf_matrix = nn_results['Confusion Matrix']
print("Confusion Matrix:")
print(conf_matrix)
print(f"ROC AUC: {nn_results['ROC AUC']:.4f}")
print(f"Accuracy: {nn_results['Accuracy']:.4f}")
print(f"F1 Score: {nn_results['F1 Score']:.4f}")
print(f"Precision: {nn_results['Precision']:.4f}")
print(f"Recall: {nn_results['Recall']:.4f}")

feature_importances = model_smote.feature_importances_

# Plot feature importance
features = ['Transaction Amount', 'Amount_zscore','Payment Method', 'Product Category', 'Quantity','Quantity_Log',
                   'Customer Age', 'Age_Category','Device Used', 'Account Age Days','Account_Age_Weeks',
                   'Transaction Hour','Hour_Bin']
plt.figure(figsize=(12, 8))
plt.barh(features, feature_importances)
plt.xlabel('Feature Importance')
plt.ylabel('Feature')
plt.title('Feature Importance')
plt.show()

base_models = {
    'LogisticRegression': model_logistic,
    'XGBoost': model_xgbooster,
    'RandomForest': model_smote
}

# Ensemble Model
class EnsembleModel:
    def __init__(self, base_models, nn_model):
        self.base_models = base_models
        self.nn_model = nn_model
        self.weights = None

    def train(self, X_val, y_val):
        base_preds = np.column_stack([model.predict_proba(X_val)[:, 1] for model in self.base_models.values()])
        nn_preds = self.nn_model.model.predict(X_val).flatten()
        all_preds = np.column_stack([base_preds, nn_preds])

        # Use logistic regression to find optimal weights
        meta_model = LogisticRegression()
        meta_model.fit(all_preds, y_val)
        self.weights = meta_model.coef_[0] / np.sum(meta_model.coef_[0])

    def predict(self, X_val):
        base_preds = np.column_stack([model.predict_proba(X_val)[:, 1] for model in self.base_models.values()])
        nn_preds = self.nn_model.model.predict(X_val).flatten()
        all_preds = np.column_stack([base_preds, nn_preds])
        return np.dot(all_preds, self.weights)

    def evaluate(self, X_val, y_val):
        y_prob = self.predict(X_val)
        y_pred = (y_prob > 0.5).astype(int)
        fpr, tpr, _ = roc_curve(y_val, y_prob)
        roc_auc = auc(fpr, tpr)
        accuracy = accuracy_score(y_val, y_pred)
        precision = precision_score(y_val, y_pred)
        recall = recall_score(y_val, y_pred)
        f1 = f1_score(y_val, y_pred)
        confusion = confusion_matrix(y_val, y_pred)
        return {
            'ROC AUC': roc_auc,
            'Accuracy': accuracy,
            'F1 Score': f1,
            'Precision': precision,
            'Recall': recall,
            'y_prob': y_prob,
            'Confusion Matrix': confusion
        }

ensemble_model = EnsembleModel(base_models=base_models, nn_model=nn_model)

# Train the ensemble model using the validation data
ensemble_model.train(X_test, y_test)  # Since you only have train/test

# Evaluate ensemble model on test data
ensemble_results = ensemble_model.evaluate(X_test, y_test)

# Print results
print("Confusion Matrix:\n", ensemble_results['Confusion Matrix'])
print("ROC AUC:", ensemble_results['ROC AUC'])
print("Accuracy:", ensemble_results['Accuracy'])
print("Precision:", ensemble_results['Precision'])
print("Recall:", ensemble_results['Recall'])
print("F1 Score:", ensemble_results['F1 Score'])

import joblib
import pickle

# Save traditional ML models
joblib.dump(model_logistic, 'logistic_model.pkl')
joblib.dump(model_xgbooster, 'xgboost_model.pkl')
joblib.dump(model_smote, 'random_forest_model.pkl')

# Save Keras Neural Network
nn_model.model.save('neural_network_model.h5')

# Save Ensemble model weights
ensemble_data = {
    'weights': ensemble_model.weights,
    'base_model_names': list(base_models.keys())
}
with open('ensemble_model.pkl', 'wb') as f:
    pickle.dump(ensemble_data, f)